#!/bin/zsh

export DOTFILES_HOME="$HOME/.shell"
export DOTFILES_VIM="$DOTFILES_HOME/vim"
export DOTFILES_ZSH="$DOTFILES_HOME/zsh"

# Things we want to load in order
typeset -a load_order
load_order=("default" "arch/$(uname)" "host/$(hostname -s)" "custom")

for lo in $load_order; do
  f=${DOTFILES_HOME}/zsh/source/$lo/*.env(N)
  for file ($DOTFILES_HOME/zsh/source/$lo/*.env(N)); do
    source $file
  done
done

[ -f "${HOME}/.zshenv.priv" ] \
    && source "${HOME}/.zshenv.priv"

typeset -U path
