#!/bin/zsh

# Load functions first
fpath=($DOTFILES_HOME/zsh/functions $fpath)

# Things we want to load in order
typeset -a load_order
load_order=("default" "arch/$(uname)" "host/$(hostname -s)" "custom")

for lo in $load_order; do
  for file ($DOTFILES_HOME/zsh/source/$lo/*.zsh(N)); do
    source $file
  done
done


SAVEHIST=1000
HISTFILE=~/.zsh_history

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/nicolas/.sdkman"
[[ -s "/Users/nicolas/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/nicolas/.sdkman/bin/sdkman-init.sh"
